FROM jedi_base_image

WORKDIR /app

COPY . .

# Run FAISS index builder script
RUN python tools/build_faiss_index.py

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]